### ISSUE TITLE
Failed to create transferConfig

### ISSUE THREAD

**Issue by omer-akhter** [googleapis/nodejs-bigquery-data-transfer#424]
#### Environment details

  - OS: macOS Catalina (10.15.7)
  - Node.js version: 12.11.1
  - npm version: 6.11.3
  - `@google-cloud/bigquery-data-transfer` version: 2.1.2

#### Steps to reproduce

I trying to create TransferConfig using SDK. But getting this strange error.

```
let transferConfigParams = {
  data_path_template: 'gs://my_bucket/dataset1/{run_time-24h|"%Y%m%d"}/**/*.jsonl',
  destination_table_name_template: '{run_time-24h|"%Y%m%d"}_jsonl',
  file_format: 'JSON',
  ignore_unknown_values: true,
  delete_source_files: true,
  write_disposition: 'APPEND'
}

transferConfigParams = _.mapValues(transferConfigParams, (value) => {
  switch (typeof value) {
    case 'boolean':
      return { boolValue: value }
    case 'number':
      return { numberValue: value }
    case 'string':
      return { stringValue: value }
    default:
      throw Error('not implemented transfer config parameter type');
  }
});

let transferConfig = protos.google.cloud.bigquery.datatransfer.v1.TransferConfig.fromObject({
  displayName: 'dataset1-transfer',
  dataSourceId: ['google_cloud_storage'],
  params: { fields: transferConfigParams },
  scheduleOptions: {
    disableAutoScheduling: true
  },
  destinationDatasetId: 'dataset1'
});

let parent = client.projectPath(await this.client.getProjectId())
let request = {
  parent: `${parent}/locations/us`,
  transferConfig
};

await client.createTransferConfig(request)
```

Here are the logs

```
DEBUG: creating transfer config
    request: {
      "parent": "projects/my_project/locations/us",
      "transferConfig": {
        "destinationDatasetId": "dataset1",
        "displayName": "dataset1-transfer",
        "dataSourceId": "google_cloud_storage",
        "params": {
          "fields": {
            "data_path_template": {
              "stringValue": "gs://my_bucket/dataset1/{run_time-24h|\"%Y%m%d\"}/**/*.jsonl"
            },
            "destination_table_name_template": {
              "stringValue": "{run_time-24h|\"%Y%m%d\"}_jsonl"
            },
            "file_format": {
              "stringValue": "JSON"
            },
            "ignore_unknown_values": {
              "boolValue": true
            },
            "delete_source_files": {
              "boolValue": true
            },
            "write_disposition": {
              "stringValue": "APPEND"
            }
          }
        },
        "scheduleOptions": {
          "disableAutoScheduling": true
        }
      }
    }    

ERROR: Correlation: 9c616336-1029-4b25-9f7a-45badba1ad8d; could not create transfer config
    error: "Error: 3 INVALID_ARGUMENT: Parameter type required for destination_table_name_template: STRING, Parameter type provided in transfer config: bool_value. Config name: 
    at Object.callErrorFromStatus (/home/me/code/gamecorecommendsvc/nodejs/node_modules/libutil/node_modules/@google-cloud/bigquery-data-transfer/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/me/code/gamecorecommendsvc/nodejs/node_modules/libutil/node_modules/@google-cloud/bigquery-data-transfer/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/home/me/code/gamecorecommendsvc/nodejs/node_modules/libutil/node_modules/@google-cloud/bigquery-data-transfer/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/home/me/code/gamecorecommendsvc/nodejs/node_modules/libutil/node_modules/@google-cloud/bigquery-data-transfer/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at /home/me/code/gamecorecommendsvc/nodejs/node_modules/libutil/node_modules/@google-cloud/bigquery-data-transfer/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)"
```

Note that I can successfully create this config using API Explorer

**Comment by chuyuou** [comment]
Hello, is there any udpate on this issue? I run into the same issue...

**Comment by steffnay** [comment]
I am looking at this issue now. Will update as soon as I can.

**Comment by steffnay** [comment]
When I try to reproduce this, I get the following error: 

`'Parameter destination_table_name_template with value {run_time-24h|\'%Y%m%d"}_jsonl does not meet the required regular expression: ^([A-z0-9_$]*|{([A-z0-9\\"%+\\-|\\\\\\.;])+})*$. Config name: '`
