### ISSUE TITLE
Missing transfer config name for updateTransferConfig

### ISSUE THREAD

**Issue by wheel1992** [googleapis/nodejs-bigquery-data-transfer#505]
#### Environment details

  - OS: macOs Big Sur
  - Node.js version: `14.17.5`
  - npm version: `6.14.14`
  - `@google-cloud/bigquery-data-transfer` version: `^2.3.0`

#### Steps to reproduce

I am trying to update a transfer config with the following code

```js

const client = new DataTransferServiceClient({
      keyFilename: "..."
      projectId: "..."
    });

await client.updateTransferConfig({
      transferConfig: {
        disabled: true,
      },
      updateMask: { paths: ['disabled'] },
    });

```

However, it returns the following error

```
UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Invalid transfer config name.
    at Object.callErrorFromStatus (/Users/joseph.chengby/Documents/Projects/appops-scheduler/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/joseph.chengby/Documents/Projects/appops-scheduler/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/Users/joseph.chengby/Documents/Projects/appops-scheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/joseph.chengby/Documents/Projects/appops-scheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/joseph.chengby/Documents/Projects/appops-scheduler/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11
```

May I know where do we set the project location transfer config path? 

As I saw other apis such as `createTransferConfig`, there is a `parent` parameter to input the path.

**Comment by wheel1992** [comment]
Hi @steffnay , any updates on this issue?

**Comment by steffnay** [comment]
Hey @wheel1992 you want to use a transferConfig object when updating. This flow should work for you:
```
  const name = 'projects/{project}/locations/{location}/transferConfigs/{transferConfig}';
  const request = {
    name,
  };

  const [config] = await client.getTransferConfig(request);

  config.disabled = true;
  const [resp] = await client.updateTransferConfig({
    transferConfig: config,
    updateMask: { paths: ['disabled'] },
  });
```
